import { Sidebar } from "components/Sidebar";
import Report from "components/Report";
import Head from "next/head";
import Link from "next/link";
import { api } from "y/utils/api";

export default function Home() {
  const reports: string[] = [" ", " ", " ", " ", " ", " ", " ", " ", " ", " "];
  return (
    <>
      <Head>
        <title>Recall</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Example></Example> */}
      <Sidebar>
        <div className="ml-5">
          <div className="flex justify-between">
            <div>
              <h1 className="text-4xl font-bold tracking-tight text-slate-900 dark:text-white sm:text-5xl lg:text-6xl">
                Dashboard -
              </h1>
              <h1 className="text-4xl font-extrabold tracking-tight text-slate-900 dark:text-white sm:text-5xl lg:text-6xl">
                JUNE 2 - 8, 2023 ACTIVITY
              </h1>
            </div>
            <div className="mr-5 flex flex-col">
              <button
                type="button"
                className="my-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Change Date Range
              </button>
              <button
                type="button"
                className="my-2 rounded-md bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600"
              >
                Generate Report
              </button>
            </div>
          </div>
        </div>
        <div className="m-5 space-y-5">
          {reports.map((e, i) => (
            <Report key={i} />
          ))}
        </div>
      </Sidebar>
    </>
  );
}
